name 'aws-psp'
maintainer 'Thomas Heinen'
maintainer_email 'theinen@tecracer.de'
issues_url 'https://github.com/tecracer-theinen/aws-psp'
source_url 'https://github.com/tecracer-theinen/aws-psp'
license 'Apache-2.0'
description 'Chef PSP for AWS'
version '0.1.0'
chef_version '>= 18.0.0'
