# Import API specifics
use "awscc_base"

resource_name :aws_apigateway_v2_route
provides :aws_apigateway_v2_route, target_mode: true, platform: "aws"

description <<~DESCRIPTION
  The ``AWS::ApiGatewayV2::Route`` resource creates a route for an API.
DESCRIPTION

property :name, String,
         name_property: true,
         description: "Name of the resource, not desired state"

property :api_id, String,
         required: true,
         callbacks: {
           "api_id is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The API identifier.
         DESCRIPTION

property :api_key_required, [TrueClass, FalseClass],
         callbacks: {
           "api_key_required is not a Boolean" => lambda { |v| v.is_a? Boolean },
         },
         description: <<~'DESCRIPTION'
           Specifies whether an API key is required for the route. Supported only for WebSocket APIs.
         DESCRIPTION

property :authorization_scopes, Array,
         callbacks: {
           "authorization_scopes is not a Array" => lambda { |v| v.is_a? Array },
         },
         description: <<~'DESCRIPTION'
           The authorization scopes supported by this route.
         DESCRIPTION

property :authorization_type, String,
         callbacks: {
           "authorization_type is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The authorization type for the route. For WebSocket APIs, valid values are ``NONE`` for open access, ``AWS_IAM`` for using AWS IAM permissions, and ``CUSTOM`` for using a Lambda authorizer. For HTTP APIs, valid values are ``NONE`` for open access, ``JWT`` for using JSON Web Tokens, ``AWS_IAM`` for using AWS IAM permissions, and ``CUSTOM`` for using a Lambda authorizer.
         DESCRIPTION

property :authorizer_id, String,
         callbacks: {
           "authorizer_id is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The identifier of the ``Authorizer`` resource to be associated with this route. The authorizer identifier is generated by API Gateway when you created the authorizer.
         DESCRIPTION

property :model_selection_expression, String,
         callbacks: {
           "model_selection_expression is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The model selection expression for the route. Supported only for WebSocket APIs.
         DESCRIPTION

property :operation_name, String,
         callbacks: {
           "operation_name is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The operation name for the route.
         DESCRIPTION

property :request_models, Hash,
         callbacks: {
           "request_models is not a Object" => lambda { |v| v.is_a? Object },
         },
         description: <<~'DESCRIPTION'
           The request models for the route. Supported only for WebSocket APIs.
         DESCRIPTION

property :request_parameters, Hash,
         callbacks: {
           "request_parameters is not a Object" => lambda { |v| v.is_a? Object },
         },
         description: <<~'DESCRIPTION'
           The request parameters for the route. Supported only for WebSocket APIs.
         DESCRIPTION

property :route_key, String,
         required: true,
         callbacks: {
           "route_key is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The route key for the route. For HTTP APIs, the route key can be either ``$default``, or a combination of an HTTP method and resource path, for example, ``GET /pets``.
         DESCRIPTION

property :route_response_selection_expression, String,
         callbacks: {
           "route_response_selection_expression is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The route response selection expression for the route. Supported only for WebSocket APIs.
         DESCRIPTION

property :target, String,
         callbacks: {
           "target is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The target for the route.
         DESCRIPTION

# API URLs and mappings
rest_api_collection "/AWS::ApiGatewayV2::Route"
rest_api_document "/AWS::ApiGatewayV2::Route"

rest_property_map({
  api_id:                              "ApiId",
  api_key_required:                    "ApiKeyRequired",
  authorization_scopes:                "AuthorizationScopes",
  authorization_type:                  "AuthorizationType",
  authorizer_id:                       "AuthorizerId",
  model_selection_expression:          "ModelSelectionExpression",
  operation_name:                      "OperationName",
  request_models:                      "RequestModels",
  request_parameters:                  "RequestParameters",
  route_key:                           "RouteKey",
  route_response_selection_expression: "RouteResponseSelectionExpression",
  target:                              "Target",
})

rest_post_only_properties %i{
  api_id
}
