# Import API specifics
use "awscc_base"

unified_mode true
resource_name :aws_rds_event_subscription
provides :aws_rds_event_subscription, target_mode: true, platform: "aws"

description <<~DESCRIPTION
  The AWS::RDS::EventSubscription resource allows you to receive notifications for Amazon Relational Database Service events through the Amazon Simple Notification Service (Amazon SNS). For more information, see Using Amazon RDS Event Notification in the Amazon RDS User Guide.
DESCRIPTION

property :name, String,
         name_property: true,
         description: "Name of the resource, not desired state"

property :enabled, [TrueClass, FalseClass],
         callbacks: {
           "enabled is not a Boolean" => lambda { |v| v.is_a? Boolean },
         },
         description: <<~'DESCRIPTION'
           A Boolean value; set to true to activate the subscription, set to false to create the subscription but not active it.
         DESCRIPTION

property :event_categories, Array,
         callbacks: {
           "event_categories is not a Array" => lambda { |v| v.is_a? Array },
         },
         description: <<~'DESCRIPTION'
           A list of event categories for a SourceType that you want to subscribe to. You can see a list of the categories for a given SourceType in the Events topic in the Amazon RDS User Guide or by using the DescribeEventCategories action.
         DESCRIPTION

property :sns_topic_arn, String,
         required: true,
         callbacks: {
           "sns_topic_arn is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The Amazon Resource Name (ARN) of the SNS topic created for event notification. The ARN is created by Amazon SNS when you create a topic and subscribe to it.
         DESCRIPTION

property :source_ids, Array,
         callbacks: {
           "source_ids is not a Array" => lambda { |v| v.is_a? Array },
         },
         description: <<~'DESCRIPTION'
           The list of identifiers of the event sources for which events will be returned. If not specified, then all sources are included in the response. An identifier must begin with a letter and must contain only ASCII letters, digits, and hyphens; it cannot end with a hyphen or contain two consecutive hyphens.
         DESCRIPTION

property :source_type, String,
         callbacks: {
           "source_type is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The type of source that will be generating the events. For example, if you want to be notified of events generated by a DB instance, you would set this parameter to db-instance. if this value is not specified, all events are returned.
         DESCRIPTION

property :subscription_name, String,
         callbacks: {
           "subscription_name is not a String" => lambda { |v| v.is_a? String },
         },
         description: <<~'DESCRIPTION'
           The name of the subscription.
         DESCRIPTION

property :tags, Array,
         callbacks: {
           "tags is not a Array" => lambda { |v| v.is_a? Array },
         },
         description: <<~'DESCRIPTION'
           An array of key-value pairs to apply to this resource.
         DESCRIPTION

# API URLs and mappings
rest_api_collection "/AWS::RDS::EventSubscription"
rest_api_document "/AWS::RDS::EventSubscription"

rest_property_map({
  enabled:           "Enabled",
  event_categories:  "EventCategories",
  sns_topic_arn:     "SnsTopicArn",
  source_ids:        "SourceIds",
  source_type:       "SourceType",
  subscription_name: "SubscriptionName",
  tags:              "Tags",
})

rest_post_only_properties %i{
  sns_topic_arn subscription_name
}
